/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author alunos
 */
public class Gerador_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Gerador_GUI
     */
    public Gerador_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Gera_BTN = new javax.swing.JButton();
        Fecha_BTN = new javax.swing.JButton();
        Limpa_BTN = new javax.swing.JButton();
        cpf_txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gerador de CPF");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(280, 20, 360, 90);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gerador de CPF");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(280, 20, 360, 90);

        Gera_BTN.setBackground(new java.awt.Color(0, 0, 0));
        Gera_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Gera_BTN.setText("GERAR");
        Gera_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gera_BTNActionPerformed(evt);
            }
        });
        jPanel4.add(Gera_BTN);
        Gera_BTN.setBounds(160, 290, 250, 90);

        Fecha_BTN.setBackground(new java.awt.Color(0, 0, 0));
        Fecha_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Fecha_BTN.setText("FECHAR");
        Fecha_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fecha_BTNActionPerformed(evt);
            }
        });
        jPanel4.add(Fecha_BTN);
        Fecha_BTN.setBounds(780, 0, 190, 80);

        Limpa_BTN.setBackground(new java.awt.Color(0, 0, 0));
        Limpa_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Limpa_BTN.setText("LIMPAR");
        Limpa_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpa_BTNActionPerformed(evt);
            }
        });
        jPanel4.add(Limpa_BTN);
        Limpa_BTN.setBounds(490, 290, 290, 90);

        cpf_txt.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        cpf_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(cpf_txt);
        cpf_txt.setBounds(240, 140, 400, 70);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 980, 400);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gerador de CPF");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(270, 0, 360, 90);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 980, 400);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerador de CPF");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(260, 10, 360, 90);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 980, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 980, 400);

        setSize(new java.awt.Dimension(974, 395));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Fecha_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fecha_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Fecha_BTNActionPerformed

    private void Limpa_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpa_BTNActionPerformed
        Controller.Config_DAO.limpa();
    }//GEN-LAST:event_Limpa_BTNActionPerformed

    private void Gera_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gera_BTNActionPerformed
        Controller.Config_DAO.Gera();
    }//GEN-LAST:event_Gera_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerador_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerador_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fecha_BTN;
    private javax.swing.JButton Gera_BTN;
    private javax.swing.JButton Limpa_BTN;
    public static javax.swing.JLabel cpf_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
